RELEASE_TAG_CHOICES = [
    ('planning', 'Planning'),
    ('planningUpdate', 'Planning update'),
    ('tender', 'Tender'),
    ('tenderAmendment', 'Tender amendment'),
    ('tenderUpdate', 'Tender update'),
    ('tenderCancellation', 'Tender cancellation'),
    ('award', 'Award'),
    ('awardUpdate', 'Award update'),
    ('awardCancellation', 'Award cancellation'),
    ('contract', 'Contract'),
    ('contractUpdate', 'Contract update'),
    ('contractAmendment', 'Contract amendment'),
    ('implementation', 'Implementation'),
    ('implementationUpdate', 'Implementation update'),
    ('contractTermination', 'Contract termination'),
    ('compiled', 'Compiled record'),
]
