# Generated by Django 3.1.13 on 2021-12-30 10:16

from django.db import migrations, models
import django.db.models.deletion
import ocds_release.custom_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocds_contracts', '0001_initial'),
        ('ocds_awards', '0001_initial'),
        ('ocds_master_tables', '0001_initial'),
        ('ocds_planning', '0001_initial'),
        ('ocds_tender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocid', models.CharField(max_length=255)),
                ('implementation_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ocds_master_tables.address')),
                ('implementation_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ocds_master_tables.value')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocid', models.CharField(editable=False, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tag', ocds_release.custom_fields.ChoiceArrayField(base_field=models.CharField(choices=[('planning', 'Planning'), ('planningUpdate', 'Planning update'), ('tender', 'Tender'), ('tenderAmendment', 'Tender amendment'), ('tenderUpdate', 'Tender update'), ('tenderCancellation', 'Tender cancellation'), ('award', 'Award'), ('awardUpdate', 'Award update'), ('awardCancellation', 'Award cancellation'), ('contract', 'Contract'), ('contractUpdate', 'Contract update'), ('contractAmendment', 'Contract amendment'), ('implementation', 'Implementation'), ('implementationUpdate', 'Implementation update'), ('contractTermination', 'Contract termination'), ('compiled', 'Compiled record')], max_length=255), size=None)),
                ('initiation_type', models.CharField(choices=[('tender', 'Tender')], default='tender', max_length=255)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='releases', to='ocds_tender.buyer')),
                ('planning', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_planning.planning')),
                ('ref_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compiled_release', to='ocds_release.record')),
                ('tender', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_tender.tender')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseParty',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.entity')),
                ('role', ocds_release.custom_fields.ChoiceArrayField(base_field=models.CharField(choices=[('buyer', 'Buyer'), ('procuringEntity', 'Procuring Entity'), ('supplier', 'Supplier'), ('tenderer', 'Tenderer'), ('funder', 'Funder'), ('enquirer', 'Enquirer'), ('payer', 'Payer'), ('payee', 'Payee'), ('reviewBody', 'Review Body'), ('interestedParty', 'Interested Party')], max_length=255), null=True, size=None)),
                ('ref_release', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parties', to='ocds_release.release')),
            ],
            bases=('ocds_master_tables.entity',),
        ),
        migrations.CreateModel(
            name='ReleaseContract',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_contracts.contract')),
                ('ref_release', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contracts', to='ocds_release.release')),
            ],
            bases=('ocds_contracts.contract',),
        ),
        migrations.CreateModel(
            name='ReleaseAward',
            fields=[
                ('award_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_awards.award')),
                ('ref_release', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='awards', to='ocds_release.release')),
            ],
            bases=('ocds_awards.award',),
        ),
        migrations.AddField(
            model_name='record',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ocds_release.target'),
        ),
        migrations.CreateModel(
            name='PublishedRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.JSONField()),
                ('ref_record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='releases', to='ocds_release.record')),
            ],
        ),
    ]
