# Generated by Django 3.1.13 on 2022-01-02 14:59

from django.db import migrations, models
import django.db.models.deletion
import ocds_release.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_implementation', '0002_auto_20220102_1459'),
        ('ocds_tender', '0001_initial'),
        ('ocds_awards', '0002_auto_20220102_1459'),
        ('ocds_master_tables', '0002_delete_organization'),
        ('ocds_contracts', '0001_initial'),
        ('ocds_release', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', ocds_release.custom_fields.ChoiceArrayField(base_field=models.CharField(choices=[('buyer', 'Buyer'), ('procuringEntity', 'Procuring Entity'), ('supplier', 'Supplier'), ('tenderer', 'Tenderer'), ('funder', 'Funder'), ('enquirer', 'Enquirer'), ('payer', 'Payer'), ('payee', 'Payee'), ('reviewBody', 'Review Body'), ('interestedParty', 'Interested Party')], max_length=255), null=True, size=None)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_master_tables.entity')),
            ],
        ),
        migrations.RemoveField(
            model_name='releasecontract',
            name='contract_ptr',
        ),
        migrations.RemoveField(
            model_name='releasecontract',
            name='ref_release',
        ),
        migrations.RemoveField(
            model_name='releaseparty',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='releaseparty',
            name='ref_release',
        ),
        migrations.AlterField(
            model_name='release',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='releases', to='ocds_master_tables.entity'),
        ),
        migrations.DeleteModel(
            name='ReleaseAward',
        ),
        migrations.DeleteModel(
            name='ReleaseContract',
        ),
        migrations.DeleteModel(
            name='ReleaseParty',
        ),
        migrations.AddField(
            model_name='role',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_release.release'),
        ),
        migrations.AddField(
            model_name='release',
            name='parties',
            field=models.ManyToManyField(through='ocds_release.Role', to='ocds_master_tables.Entity'),
        ),
    ]
