# Generated by Django 3.1.13 on 2021-11-19 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_awards', '0002_auto_20211119_0605'),
        ('ocds_contracts', '0003_auto_20211119_0605'),
        ('ocds_master_tables', '0008_auto_20211119_0641'),
        ('ocds_tender', '0007_auto_20211119_0658'),
        ('ocds_release', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseParty',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.entity')),
            ],
            bases=('ocds_master_tables.entity',),
        ),
        migrations.AddField(
            model_name='release',
            name='buyer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='initiation_type',
            field=models.CharField(choices=[('tender', 'Tender')], default='tender', max_length=255),
        ),
        migrations.AddField(
            model_name='release',
            name='tender',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_tender.tender'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReleasePartyRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('buyer', 'Buyer'), ('procuringEntity', 'Procuring Entity'), ('supplier', 'Supplier'), ('tenderer', 'Tenderer'), ('funder', 'Funder'), ('enquirer', 'Enquirer'), ('payer', 'Payer'), ('payee', 'Payee'), ('reviewBody', 'Review Body'), ('interestedParty', 'Interested Party')], max_length=255)),
                ('ref_release_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_release.releaseparty')),
            ],
        ),
        migrations.AddField(
            model_name='releaseparty',
            name='ref_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_release.release'),
        ),
        migrations.CreateModel(
            name='ReleaseContract',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_contracts.contract')),
                ('ref_release', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_release.release')),
            ],
            bases=('ocds_contracts.contract',),
        ),
        migrations.CreateModel(
            name='ReleaseAward',
            fields=[
                ('award_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_awards.award')),
                ('ref_release', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_release.release')),
            ],
            bases=('ocds_awards.award',),
        ),
    ]
