# Generated by Django 3.1.13 on 2022-01-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_release', '0002_auto_20220102_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='ocid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='ocid',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
