# Generated by Django 3.1.13 on 2021-12-30 18:09

from django.db import migrations, models
import django.db.models.deletion
import ocds_release.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0002_delete_organization'),
        ('ocds_release', '0002_auto_20211230_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', ocds_release.custom_fields.ChoiceArrayField(base_field=models.CharField(choices=[('buyer', 'Buyer'), ('procuringEntity', 'Procuring Entity'), ('supplier', 'Supplier'), ('tenderer', 'Tenderer'), ('funder', 'Funder'), ('enquirer', 'Enquirer'), ('payer', 'Payer'), ('payee', 'Payee'), ('reviewBody', 'Review Body'), ('interestedParty', 'Interested Party')], max_length=255), null=True, size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='releaseparty',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='releaseparty',
            name='ref_release',
        ),
        migrations.AlterField(
            model_name='release',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='releases', to='ocds_master_tables.entity'),
        ),
    ]
