# Generated by Django 3.1.13 on 2021-11-19 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_release', '0002_auto_20211119_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compiled_release', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_release.release')),
            ],
        ),
        migrations.AddField(
            model_name='release',
            name='ref_record',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_release.record'),
            preserve_default=False,
        ),
    ]
