# Generated by Django 3.1.13 on 2021-11-21 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_tender', '0008_auto_20211121_0714'),
        ('ocds_master_tables', '0009_budget_projet'),
        ('ocds_planning', '0003_auto_20211121_0717'),
        ('ocds_release', '0003_auto_20211119_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='planning',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_planning.planning'),
        ),
        migrations.AlterField(
            model_name='record',
            name='compiled_release',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_release.release'),
        ),
        migrations.AlterField(
            model_name='release',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.entity'),
        ),
        migrations.AlterField(
            model_name='release',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='ocid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='ref_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_release.record'),
        ),
        migrations.AlterField(
            model_name='release',
            name='tender',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_tender.tender'),
        ),
    ]
