# Generated by Django 3.1.13 on 2021-12-30 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_tender', '0003_auto_20211230_1809'),
        ('ocds_awards', '0003_auto_20211230_1809'),
        ('ocds_implementation', '0003_auto_20211230_1809'),
        ('ocds_release', '0003_auto_20211230_1809'),
        ('ocds_master_tables', '0002_delete_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReleaseParty',
        ),
        migrations.AddField(
            model_name='role',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_master_tables.entity'),
        ),
        migrations.AddField(
            model_name='role',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_release.release'),
        ),
        migrations.AddField(
            model_name='release',
            name='parties',
            field=models.ManyToManyField(through='ocds_release.Role', to='ocds_master_tables.Entity'),
        ),
    ]
