# Generated by Django 3.1.13 on 2022-01-01 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_contracts', '0001_initial'),
        ('ocds_implementation', '0003_auto_20211230_1809'),
        ('ocds_awards', '0004_award_release'),
        ('ocds_release', '0004_auto_20211230_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasecontract',
            name='contract_ptr',
        ),
        migrations.RemoveField(
            model_name='releasecontract',
            name='ref_release',
        ),
        migrations.DeleteModel(
            name='ReleaseAward',
        ),
        migrations.DeleteModel(
            name='ReleaseContract',
        ),
    ]
