# Generated by Django 3.1.13 on 2021-12-02 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_tender', '0009_auto_20211202_1115'),
        ('ocds_release', '0004_auto_20211121_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_tender.buyer'),
        ),
    ]
