# Generated by Django 3.1.13 on 2021-12-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_planning', '0004_auto_20211121_0910'),
        ('ocds_tender', '0009_auto_20211202_1115'),
        ('ocds_release', '0005_auto_20211202_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_planning.planning'),
        ),
        migrations.AlterField(
            model_name='release',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_tender.tender'),
        ),
    ]
