# Generated by Django 3.1.13 on 2021-12-10 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_release', '0006_auto_20211209_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='ocid',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='ocid',
            field=models.CharField(default=0, editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='ref_record',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_release.record'),
            preserve_default=False,
        ),
    ]
