# Generated by Django 3.1.13 on 2021-12-12 11:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_release', '0007_auto_20211210_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseparty',
            name='role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('buyer', 'Buyer'), ('procuringEntity', 'Procuring Entity'), ('supplier', 'Supplier'), ('tenderer', 'Tenderer'), ('funder', 'Funder'), ('enquirer', 'Enquirer'), ('payer', 'Payer'), ('payee', 'Payee'), ('reviewBody', 'Review Body'), ('interestedParty', 'Interested Party')], max_length=255), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='release',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('planning', 'Planning'), ('planningUpdate', 'Planning update'), ('tender', 'Tender'), ('tenderAmendment', 'Tender amendment'), ('tenderUpdate', 'Tender update'), ('tenderCancellation', 'Tender cancellation'), ('award', 'Award'), ('awardUpdate', 'Award update'), ('awardCancellation', 'Award cancellation'), ('contract', 'Contract'), ('contractUpdate', 'Contract update'), ('contractAmendment', 'Contract amendment'), ('implementation', 'Implementation'), ('implementationUpdate', 'Implementation update'), ('contractTermination', 'Contract termination'), ('compiled', 'Compiled record')], max_length=255), size=None),
        ),
        migrations.DeleteModel(
            name='ReleasePartyRole',
        ),
    ]
