# Generated by Django 3.1.13 on 2021-12-12 12:56

from django.db import migrations, models
import django.db.models.deletion
import ocds_release.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_release', '0008_auto_20211212_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='compiled_release',
        ),
        migrations.AlterField(
            model_name='release',
            name='ref_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compiled_release', to='ocds_release.record'),
        ),
        migrations.AlterField(
            model_name='release',
            name='tag',
            field=ocds_release.custom_fields.ChoiceArrayField(base_field=models.CharField(choices=[('planning', 'Planning'), ('planningUpdate', 'Planning update'), ('tender', 'Tender'), ('tenderAmendment', 'Tender amendment'), ('tenderUpdate', 'Tender update'), ('tenderCancellation', 'Tender cancellation'), ('award', 'Award'), ('awardUpdate', 'Award update'), ('awardCancellation', 'Award cancellation'), ('contract', 'Contract'), ('contractUpdate', 'Contract update'), ('contractAmendment', 'Contract amendment'), ('implementation', 'Implementation'), ('implementationUpdate', 'Implementation update'), ('contractTermination', 'Contract termination'), ('compiled', 'Compiled record')], max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='releaseparty',
            name='role',
            field=ocds_release.custom_fields.ChoiceArrayField(base_field=models.CharField(choices=[('buyer', 'Buyer'), ('procuringEntity', 'Procuring Entity'), ('supplier', 'Supplier'), ('tenderer', 'Tenderer'), ('funder', 'Funder'), ('enquirer', 'Enquirer'), ('payer', 'Payer'), ('payee', 'Payee'), ('reviewBody', 'Review Body'), ('interestedParty', 'Interested Party')], max_length=255), null=True, size=None),
        ),
        migrations.CreateModel(
            name='PublishedRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.JSONField()),
                ('ref_record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='release_set', to='ocds_release.record')),
            ],
        ),
    ]
