# Generated by Django 3.1.13 on 2021-12-12 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_release', '0009_auto_20211212_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseaward',
            name='ref_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='awards', to='ocds_release.release'),
        ),
        migrations.AlterField(
            model_name='releasecontract',
            name='ref_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contracts', to='ocds_release.release'),
        ),
        migrations.AlterField(
            model_name='releaseparty',
            name='ref_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parties', to='ocds_release.release'),
        ),
    ]
