version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  nuxt:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: transparencyportal_local_nuxt
    container_name: nuxt_marche
    depends_on:
      - django
    ports:
      - "3001:3001"
  django:
    build:
      context: ./server
      dockerfile: ./compose/local/django/Dockerfile
    image: transparencyportal_local_django
    container_name: django_marche
    depends_on:
      - postgres
    volumes:
      - ./server:/app:z
    env_file:
      - ./server/.envs/.local/.django
      - ./server/.envs/.local/.postgres
    ports:
      - "8001:8001"
    command: /start

  postgres:
    build:
      context: ./server
      dockerfile: ./compose/production/postgres/Dockerfile
    image: transparencyportal_production_postgres
    container_name: postgres_marche
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./server/.envs/.local/.postgres

