# Generated by Django 3.1.13 on 2021-11-18 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocds_master_tables', '0004_auto_20211117_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('uri', models.CharField(max_length=255)),
                ('amount', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocds_master_tables.value')),
                ('implementation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_implementation.implementation')),
                ('provider_organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provider_organization', to='ocds_master_tables.entity')),
                ('receiver_organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_organization', to='ocds_master_tables.entity')),
            ],
        ),
        migrations.CreateModel(
            name='ImplementationMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('due_date', models.CharField(max_length=255)),
                ('date_modified', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('ref_implementation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_implementation.implementation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImplementationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('document_format', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('ref_implementation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_implementation.implementation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
