# Generated by Django 3.1.13 on 2021-11-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0005_milestone_milestonedocument'),
        ('ocds_implementation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implementationmilestone',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='implementationmilestone',
            name='description',
        ),
        migrations.RemoveField(
            model_name='implementationmilestone',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='implementationmilestone',
            name='id',
        ),
        migrations.RemoveField(
            model_name='implementationmilestone',
            name='status',
        ),
        migrations.RemoveField(
            model_name='implementationmilestone',
            name='title',
        ),
        migrations.AddField(
            model_name='implementationmilestone',
            name='milestone_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.milestone'),
            preserve_default=False,
        ),
    ]
