# Generated by Django 3.1.13 on 2021-12-30 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0002_delete_organization'),
        ('ocds_implementation', '0002_auto_20211230_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_payee_transactions', to='ocds_master_tables.entity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_payer_transactions', to='ocds_master_tables.entity'),
        ),
    ]
