# Generated by Django 3.1.13 on 2021-11-19 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0006_organization'),
        ('ocds_implementation', '0002_auto_20211118_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='provider_organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provider_organization', to='ocds_master_tables.organization'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_organization', to='ocds_master_tables.organization'),
        ),
    ]
