# Generated by Django 3.1.13 on 2023-06-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_implementation', '0002_auto_20220102_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
