# Generated by Django 3.1.13 on 2021-12-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_implementation', '0006_auto_20211212_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementationdocument',
            name='ref_implementation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ocds_implementation.implementation'),
        ),
        migrations.AlterField(
            model_name='implementationmilestone',
            name='ref_implementation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='ocds_implementation.implementation'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='implementation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ocds_implementation.implementation'),
        ),
    ]
