# Generated by Django 3.1.13 on 2021-12-30 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocds_master_tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.entity')),
            ],
            bases=('ocds_master_tables.entity',),
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('planning', 'Planning'), ('planned', 'Planned'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('unsuccessful', 'Unsuccessful'), ('complete', 'Complete'), ('withdrawn', 'Withdrawn')], max_length=255, null=True)),
                ('procurement_method', models.CharField(blank=True, choices=[('open', 'Open'), ('selective', 'Selective'), ('limited', 'Limited'), ('direct', 'Direct')], max_length=255, null=True)),
                ('procurement_method_rationale', models.TextField(blank=True, null=True)),
                ('award_criteria', models.CharField(blank=True, choices=[('priceOnly', 'Price only'), ('costOnly', 'Cost only'), ('qualityOnly', 'Quality only'), ('ratedCriteria', 'Rated criteria'), ('lowestCost', 'Lowest cost'), ('bestProposal', 'Best proposal'), ('bestValueToGovernment', 'Best value to government'), ('singleBidOnly', 'Single bid only')], max_length=255, null=True)),
                ('award_criteria_details', models.TextField(blank=True, null=True)),
                ('submission_method', models.CharField(blank=True, choices=[('electronicSubmission', 'Electronic submission'), ('electronicAuction', 'Electronic auction'), ('written', 'Written'), ('inPerson', 'In person')], max_length=255, null=True)),
                ('submission_method_details', models.TextField(blank=True, null=True)),
                ('has_enquiries', models.BooleanField(default=False)),
                ('eligibility_criteria', models.TextField(blank=True, null=True)),
                ('award_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_award_period_tenders', to='ocds_master_tables.period')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenders', to='ocds_tender.buyer')),
                ('enquiry_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_enquiry_period_tenders', to='ocds_master_tables.period')),
                ('min_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_min_value_tenders', to='ocds_master_tables.value')),
                ('procuring_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_procuring_entity_tenders', to='ocds_master_tables.entity')),
                ('tender_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_tender_period_tenders', to='ocds_master_tables.period')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_default_value_tenders', to='ocds_master_tables.value')),
            ],
        ),
        migrations.CreateModel(
            name='TenderMilestone',
            fields=[
                ('milestone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.milestone')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='milestones', to='ocds_tender.tender')),
            ],
            bases=('ocds_master_tables.milestone',),
        ),
        migrations.CreateModel(
            name='TenderItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.item')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ocds_tender.tender')),
            ],
            bases=('ocds_master_tables.item',),
        ),
        migrations.CreateModel(
            name='Tenderer',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.entity')),
                ('ref_tender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenderers', to='ocds_tender.tender')),
            ],
            bases=('ocds_master_tables.entity',),
        ),
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.document')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='ocds_tender.tender')),
            ],
            bases=('ocds_master_tables.document',),
        ),
        migrations.CreateModel(
            name='TenderAmendment',
            fields=[
                ('amendment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.amendment')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='ocds_tender.tender')),
            ],
            bases=('ocds_master_tables.amendment',),
        ),
    ]
