# Generated by Django 3.1.13 on 2021-12-30 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_release', '0002_auto_20211230_0904'),
        ('ocds_master_tables', '0002_delete_organization'),
        ('ocds_tender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderer',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='tenderer',
            name='ref_tender',
        ),
        migrations.AddField(
            model_name='tender',
            name='tenderers',
            field=models.ManyToManyField(related_name='as_tenderers', to='ocds_release.ReleaseParty'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenders', to='ocds_release.releaseparty'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='procuring_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_procuring_entity_tenders', to='ocds_release.releaseparty'),
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Tenderer',
        ),
    ]
