# Generated by Django 3.1.13 on 2022-01-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0002_delete_organization'),
        ('ocds_release', '0002_auto_20220102_1459'),
        ('ocds_tender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderer',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='tenderer',
            name='ref_tender',
        ),
        migrations.AddField(
            model_name='tender',
            name='tenderers',
            field=models.ManyToManyField(related_name='as_tenderer_tenders', to='ocds_master_tables.Entity'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_buyer_tenders', to='ocds_master_tables.entity'),
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Tenderer',
        ),
    ]
