# Generated by Django 3.1.13 on 2021-11-15 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_tender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('due_date', models.CharField(max_length=255)),
                ('date_modified', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('planned', 'Planned'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('unsuccessful', 'Unsuccessful'), ('complete', 'Complete'), ('withdrawn', 'Withdrawn')], max_length=255)),
                ('procurement_method', models.CharField(choices=[('open', 'Open'), ('selective', 'Selective'), ('limited', 'Limited'), ('direct', 'Direct')], max_length=255)),
                ('procurement_method_rationale', models.TextField()),
                ('award_criteria', models.CharField(choices=[('priceOnly', 'Price only'), ('costOnly', 'Cost only'), ('qualityOnly', 'Quality only'), ('ratedCriteria', 'Rated criteria'), ('lowestCost', 'Lowest cost'), ('bestProposal', 'Best proposal'), ('bestValueToGovernment', 'Best value to government'), ('singleBidOnly', 'Single bid only')], max_length=255)),
                ('award_criteria_details', models.TextField()),
                ('submission_method', models.CharField(choices=[('electronicSubmission', 'Electronic submission'), ('electronicAuction', 'Electronic auction'), ('written', 'Written'), ('inPerson', 'In person')], max_length=255)),
                ('submission_method_details', models.TextField()),
                ('award_period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='award_period', to='ocds_tender.period')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_tender.buyer')),
                ('enquiry_period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='enquiry_period', to='ocds_tender.period')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('document_format', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_tender.tender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tender',
            name='min_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='min_value', to='ocds_tender.value'),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tender_period', to='ocds_tender.period'),
        ),
        migrations.AddField(
            model_name='tender',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='default_value', to='ocds_tender.value'),
        ),
        migrations.CreateModel(
            name='MilestoneDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('document_format', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_tender.milestone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='milestone',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_tender.tender'),
        ),
    ]
