# Generated by Django 3.1.13 on 2021-11-16 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0001_initial'),
        ('ocds_tender', '0002_auto_20211115_0759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Milestone',
            new_name='TenderMilestone',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='contact_point',
        ),
        migrations.AddField(
            model_name='tender',
            name='eligibility_criteria',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tender',
            name='has_enquiries',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tender',
            name='award_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='award_period', to='ocds_master_tables.period'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.buyer'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='enquiry_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='enquiry_period', to='ocds_master_tables.period'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='min_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='min_value', to='ocds_master_tables.value'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tender_period', to='ocds_master_tables.period'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='default_value', to='ocds_master_tables.value'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='ContactPoint',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
