# Generated by Django 3.1.13 on 2021-11-21 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0009_budget_projet'),
        ('ocds_tender', '0007_auto_20211119_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='amendment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.amendment'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='award_criteria',
            field=models.CharField(blank=True, choices=[('priceOnly', 'Price only'), ('costOnly', 'Cost only'), ('qualityOnly', 'Quality only'), ('ratedCriteria', 'Rated criteria'), ('lowestCost', 'Lowest cost'), ('bestProposal', 'Best proposal'), ('bestValueToGovernment', 'Best value to government'), ('singleBidOnly', 'Single bid only')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='award_criteria_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='award_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='award_period', to='ocds_master_tables.period'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='eligibility_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='enquiry_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enquiry_period', to='ocds_master_tables.period'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='min_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='min_value', to='ocds_master_tables.value'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='number_of_tenderers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='procurement_method',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('selective', 'Selective'), ('limited', 'Limited'), ('direct', 'Direct')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='procurement_method_rationale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='procuring_entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procuring_entity', to='ocds_master_tables.entity'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(blank=True, choices=[('planning', 'Planning'), ('planned', 'Planned'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('unsuccessful', 'Unsuccessful'), ('complete', 'Complete'), ('withdrawn', 'Withdrawn')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='submission_method',
            field=models.CharField(blank=True, choices=[('electronicSubmission', 'Electronic submission'), ('electronicAuction', 'Electronic auction'), ('written', 'Written'), ('inPerson', 'In person')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='submission_method_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tender_period', to='ocds_master_tables.period'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='default_value', to='ocds_master_tables.value'),
        ),
    ]
