# Generated by Django 3.1.13 on 2021-12-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0010_auto_20211121_0740'),
        ('ocds_tender', '0008_auto_20211121_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.entity')),
            ],
            bases=('ocds_master_tables.entity',),
        ),
        migrations.AlterField(
            model_name='tender',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_tender.buyer'),
        ),
    ]
