# Generated by Django 3.1.13 on 2021-12-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_tender', '0010_auto_20211212_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='number_of_tenderers',
        ),
        migrations.AlterField(
            model_name='tender',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenders', to='ocds_tender.buyer'),
        ),
        migrations.AlterField(
            model_name='tenderamendment',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='ocds_tender.tender'),
        ),
        migrations.AlterField(
            model_name='tenderdocument',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='ocds_tender.tender'),
        ),
        migrations.AlterField(
            model_name='tenderer',
            name='ref_tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenderers', to='ocds_tender.tender'),
        ),
        migrations.AlterField(
            model_name='tenderitem',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ocds_tender.tender'),
        ),
        migrations.AlterField(
            model_name='tendermilestone',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='milestones', to='ocds_tender.tender'),
        ),
    ]
