# Generated by Django 3.1.13 on 2021-12-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rationale', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('Code', 'Title'), ('CPV', 'EC Common Procurement Vocabulary'), ('CPVS', 'EC Common Procurement Vocabulary - Supplementary Codelists'), ('GSIN', 'Goods and Services Identification Number'), ('UNSPSC', 'United Nations Standard Products and Services Code'), ('CPC', 'Central Product Classification'), ('OKDP', 'Russian National Classification of Products by Economic Activity (1994)'), ('OKPD', 'Russian National Classification of Products by Economic Activity (2014)'), ('CUCOP', 'Mexican Single Classifier of Public Procurement'), ('NAICS', 'North American Industry Classification System'), ('PSC', 'Product and Service Codes'), ('HS', 'Harmonized Commodity Description and Coding System')], max_length=255)),
                ('description', models.TextField()),
                ('uri', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=255)),
                ('faxNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=255)),
                ('legal_name', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('due_date', models.CharField(max_length=255)),
                ('date_modified', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('met', 'Met'), ('notMet', 'Not met'), ('partiallyMet', 'Partially met')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=255)),
                ('legal_name', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_projet', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.value')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('plannedProcurementNotice', 'Notice of planned procurement'), ('tenderNotice', 'Tender notice'), ('awardNotice', 'Award notice'), ('contractNotice', 'Contract notice'), ('completionCertificate', 'Completion certificate'), ('procurementPlan', 'Procurement plan'), ('biddingDocuments', 'Bidding documents'), ('technicalSpecifications', 'Technical specifications'), ('evaluationCriteria', 'Evaluation criteria'), ('evaluationReports', 'Evaluation report'), ('contractDraft', 'Contract Draft'), ('contractSigned', 'Signed contract'), ('contractArrangements', 'Arrangements for ending contract'), ('contractSchedule', 'Contract schedules'), ('physicalProgressReport', 'Physical progress reports'), ('financialProgressReport', 'Financial progress reports'), ('finalAudit', 'Final audit'), ('hearingNotice', 'Public hearing notice'), ('marketStudies', 'Market studies'), ('eligibilityCriteria', 'Eligibility criteria'), ('clarifications', 'Clarifications to bidders questions'), ('shortlistedFirms', 'Shortlisted firms'), ('environmentalImpact', 'Environmental impact'), ('assetAndLiabilityAssessment', "Assessment of government's assets and liabilities"), ('riskProvisions', 'Provisions for management of risks and liabilities'), ('winningBid', 'Winning bid'), ('complaints', 'Complaints and decisions'), ('contractAnnexe', 'Annexes to the contract'), ('contractGuarantees', 'Guarantees'), ('subContract', 'Subcontracts'), ('needsAssessment', 'Needs assessment'), ('feasibilityStudy', 'Feasibility study'), ('projectPlan', 'Project plan'), ('billOfQuantity', 'Bill of quantity'), ('bidders', 'Information on bidders'), ('conflictOfInterest', 'Conflict of interest'), ('debarments', 'Debarments'), ('illustration', 'Illustrations'), ('submissionDocuments', 'Bid submission documents'), ('contractSummary', 'Contract summary'), ('cancellationDetails', 'Cancellation details')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('document_format', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('ref_milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_master_tables.milestone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('classification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.classification')),
                ('unit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.address')),
                ('contact_point', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.contactpoint')),
                ('identifier', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.identifier')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=255)),
                ('former_value', models.TextField(blank=True, null=True)),
                ('amendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_master_tables.amendment')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.value')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.projet')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAdditionalClassification',
            fields=[
                ('classification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.classification')),
                ('ref_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_master_tables.item')),
            ],
            bases=('ocds_master_tables.classification',),
        ),
        migrations.CreateModel(
            name='EntityAdditionalIdentifier',
            fields=[
                ('identifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.identifier')),
                ('ref_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_master_tables.entity')),
            ],
            bases=('ocds_master_tables.identifier',),
        ),
    ]
