# Generated by Django 3.1.13 on 2021-12-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_implementation', '0002_auto_20211230_0904'),
        ('ocds_master_tables', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
