# Generated by Django 3.1.13 on 2022-05-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0002_delete_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('boundary', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='region',
        ),
        migrations.AddField(
            model_name='address',
            name='region_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocds_master_tables.region'),
        ),
    ]
