# Generated by Django 3.1.13 on 2021-11-17 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0002_auto_20211116_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EntityAdditionalIdentifier',
            fields=[
                ('identifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.identifier')),
            ],
            bases=('ocds_master_tables.identifier',),
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='contact_point',
        ),
    ]
