# Generated by Django 3.1.13 on 2021-11-17 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0003_auto_20211117_2044'),
        ('ocds_tender', '0004_auto_20211117_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.AddField(
            model_name='entityadditionalidentifier',
            name='ref_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_master_tables.entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.address'),
        ),
        migrations.AddField(
            model_name='entity',
            name='contact_point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.contactpoint'),
        ),
        migrations.AddField(
            model_name='entity',
            name='identifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.identifier'),
        ),
    ]
