# Generated by Django 3.1.13 on 2021-11-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0005_milestone_milestonedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=255)),
                ('legal_name', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=255)),
            ],
        ),
    ]
