# Generated by Django 3.1.13 on 2021-11-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0008_auto_20211119_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_projet', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=255)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.value')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.projet')),
            ],
        ),
    ]
