# Generated by Django 3.1.13 on 2021-11-21 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0009_budget_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.value'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.projet'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='change',
            name='former_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='scheme',
            field=models.CharField(choices=[('Code', 'Title'), ('CPV', 'EC Common Procurement Vocabulary'), ('CPVS', 'EC Common Procurement Vocabulary - Supplementary Codelists'), ('GSIN', 'Goods and Services Identification Number'), ('UNSPSC', 'United Nations Standard Products and Services Code'), ('CPC', 'Central Product Classification'), ('OKDP', 'Russian National Classification of Products by Economic Activity (1994)'), ('OKPD', 'Russian National Classification of Products by Economic Activity (2014)'), ('CUCOP', 'Mexican Single Classifier of Public Procurement'), ('NAICS', 'North American Industry Classification System'), ('PSC', 'Product and Service Codes'), ('HS', 'Harmonized Commodity Description and Coding System')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='period',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='value',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.value'),
        ),
        migrations.AlterField(
            model_name='value',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
