# Generated by Django 3.1.13 on 2021-12-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0010_auto_20211121_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpoint',
            old_name='faxNumber',
            new_name='fax_number',
        ),
        migrations.AlterField(
            model_name='entity',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.address'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='contact_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.contactpoint'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.identifier'),
        ),
        migrations.AlterField(
            model_name='item',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.classification'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='date_modified',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='milestonedocument',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
