# Generated by Django 3.1.13 on 2021-12-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0011_auto_20211212_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='amendment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='ocds_master_tables.amendment'),
        ),
        migrations.AlterField(
            model_name='entityadditionalidentifier',
            name='ref_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_identifiers', to='ocds_master_tables.entity'),
        ),
        migrations.AlterField(
            model_name='itemadditionalclassification',
            name='ref_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_classifications', to='ocds_master_tables.item'),
        ),
        migrations.AlterField(
            model_name='milestonedocument',
            name='ref_milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ocds_master_tables.milestone'),
        ),
    ]
