# Generated by Django 3.1.13 on 2021-11-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amout', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=255)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_planning.amount')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.TextField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_planning.amount')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_planning.budget')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('document_format', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_planning.planning')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
