# Generated by Django 3.1.13 on 2021-11-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0009_budget_projet'),
        ('ocds_planning', '0002_auto_20211119_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.value'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.budget'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='raison',
            field=models.TextField(blank=True, null=True),
        ),
    ]
