# Generated by Django 3.1.13 on 2021-11-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0010_auto_20211121_0740'),
        ('ocds_planning', '0003_auto_20211121_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='amount',
        ),
        migrations.AlterField(
            model_name='planning',
            name='budget',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.budget'),
        ),
    ]
