# Generated by Django 3.1.13 on 2021-12-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0011_auto_20211212_0701'),
        ('ocds_planning', '0004_auto_20211121_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningdocument',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlanningMilestone',
            fields=[
                ('milestone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.milestone')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_planning.planning')),
            ],
            bases=('ocds_master_tables.milestone',),
        ),
    ]
