# Generated by Django 3.1.13 on 2021-11-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocds_master_tables', '0004_auto_20211117_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated')], max_length=255)),
                ('date_signed', models.DateTimeField(blank=True, null=True)),
                ('amendment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.amendment')),
                ('period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.period')),
                ('value', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.value')),
            ],
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.item')),
                ('ref_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_contracts.contract')),
            ],
            bases=('ocds_master_tables.item',),
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('document_format', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('ref_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_contracts.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
