# Generated by Django 3.1.13 on 2021-12-30 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocds_awards', '0001_initial'),
        ('ocds_master_tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated')], max_length=255)),
                ('date_signed', models.DateTimeField(blank=True, null=True)),
                ('period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.period')),
                ('ref_award', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ocds_awards.award')),
                ('value', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.value')),
            ],
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('milestone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.milestone')),
                ('ref_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='ocds_contracts.contract')),
            ],
            bases=('ocds_master_tables.milestone',),
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.item')),
                ('ref_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ocds_contracts.contract')),
            ],
            bases=('ocds_master_tables.item',),
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.document')),
                ('ref_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ocds_contracts.contract')),
            ],
            bases=('ocds_master_tables.document',),
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('amendment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.amendment')),
                ('ref_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='ocds_contracts.contract')),
            ],
            bases=('ocds_master_tables.amendment',),
        ),
    ]
