# Generated by Django 3.1.13 on 2023-06-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
