# Generated by Django 3.1.13 on 2021-11-21 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_awards', '0003_auto_20211121_0720'),
        ('ocds_contracts', '0003_auto_20211119_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ref_award',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='ocds_awards.award'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
