# Generated by Django 3.1.13 on 2021-12-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0011_auto_20211212_0701'),
        ('ocds_contracts', '0004_auto_20211121_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='amendment',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='implementation',
        ),
        migrations.AlterField(
            model_name='contractdocument',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('milestone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.milestone')),
                ('ref_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_contracts.contract')),
            ],
            bases=('ocds_master_tables.milestone',),
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('amendment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.amendment')),
                ('ref_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocds_contracts.contract')),
            ],
            bases=('ocds_master_tables.amendment',),
        ),
    ]
