# Generated by Django 3.1.13 on 2021-12-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_contracts', '0005_auto_20211212_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractamendment',
            name='ref_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='ocds_contracts.contract'),
        ),
        migrations.AlterField(
            model_name='contractdocument',
            name='ref_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ocds_contracts.contract'),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='ref_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ocds_contracts.contract'),
        ),
        migrations.AlterField(
            model_name='contractmilestone',
            name='ref_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='ocds_contracts.contract'),
        ),
    ]
