# Generated by Django 3.1.13 on 2021-11-19 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocds_master_tables', '0005_milestone_milestonedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('unsuccessful', 'Unsuccessful')], max_length=255)),
                ('date', models.DateTimeField()),
                ('contract_period', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.period')),
                ('value', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.value')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.entity')),
                ('ref_award', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_awards.award')),
            ],
            bases=('ocds_master_tables.entity',),
        ),
        migrations.CreateModel(
            name='AwardItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.item')),
                ('ref_award', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_awards.award')),
            ],
            bases=('ocds_master_tables.item',),
        ),
        migrations.CreateModel(
            name='AwardDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('document_format', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('ref_award', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_awards.award')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AwardAmendment',
            fields=[
                ('amendment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.amendment')),
                ('ref_award', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_awards.award')),
            ],
            bases=('ocds_master_tables.amendment',),
        ),
    ]
