# Generated by Django 3.1.13 on 2021-12-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocds_master_tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('unsuccessful', 'Unsuccessful')], max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('contract_period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.period')),
                ('value', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.value')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.entity')),
                ('ref_award', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='suppliers', to='ocds_awards.award')),
            ],
            bases=('ocds_master_tables.entity',),
        ),
        migrations.CreateModel(
            name='AwardItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.item')),
                ('ref_award', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='ocds_awards.award')),
            ],
            bases=('ocds_master_tables.item',),
        ),
        migrations.CreateModel(
            name='AwardDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.document')),
                ('ref_award', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='ocds_awards.award')),
            ],
            bases=('ocds_master_tables.document',),
        ),
        migrations.CreateModel(
            name='AwardAmendment',
            fields=[
                ('amendment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ocds_master_tables.amendment')),
                ('ref_award', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='amendments', to='ocds_awards.award')),
            ],
            bases=('ocds_master_tables.amendment',),
        ),
    ]
