# Generated by Django 3.1.13 on 2021-12-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_release', '0002_auto_20211230_0904'),
        ('ocds_tender', '0002_auto_20211230_0904'),
        ('ocds_master_tables', '0002_delete_organization'),
        ('ocds_awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='suppliers',
            field=models.ManyToManyField(related_name='as_suppliers', to='ocds_release.ReleaseParty'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
