# Generated by Django 3.1.13 on 2021-11-21 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0009_budget_projet'),
        ('ocds_awards', '0002_auto_20211119_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='contract_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.period'),
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('unsuccessful', 'Unsuccessful')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='value',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_master_tables.value'),
        ),
    ]
