# Generated by Django 3.1.13 on 2021-12-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_master_tables', '0002_delete_organization'),
        ('ocds_awards', '0002_auto_20211230_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='suppliers',
            field=models.ManyToManyField(related_name='as_supplier_awards', to='ocds_master_tables.Entity'),
        ),
    ]
