# Generated by Django 3.1.13 on 2022-01-01 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_release', '0004_auto_20211230_1809'),
        ('ocds_awards', '0003_auto_20211230_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocds_release.release'),
        ),
    ]
