# Generated by Django 3.1.13 on 2021-11-26 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_tender', '0008_auto_20211121_0714'),
        ('ocds_awards', '0003_auto_20211121_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='ref_tender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_tender.tender'),
            preserve_default=False,
        ),
    ]
