# Generated by Django 3.1.13 on 2022-01-01 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_release', '0005_auto_20220101_0801'),
        ('ocds_awards', '0004_award_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='ocds_release.release'),
        ),
    ]
