# Generated by Django 3.1.13 on 2021-12-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_awards', '0004_award_ref_tender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='ref_tender',
        ),
        migrations.AlterField(
            model_name='awardamendment',
            name='ref_award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocds_awards.award'),
        ),
        migrations.AlterField(
            model_name='awarddocument',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
