# Generated by Django 3.1.13 on 2021-12-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocds_awards', '0005_auto_20211212_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardamendment',
            name='ref_award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='amendments', to='ocds_awards.award'),
        ),
        migrations.AlterField(
            model_name='awarddocument',
            name='ref_award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='ocds_awards.award'),
        ),
        migrations.AlterField(
            model_name='awarditem',
            name='ref_award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='ocds_awards.award'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ref_award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='suppliers', to='ocds_awards.award'),
        ),
    ]
